site_name: 引商刻羽，杂以流徵

nav:
  - 首页: "index.md"
  # - 开发技巧文章: 
  #   - "我的常用开发技巧": "我的常用开发技巧.md"
  # - "mkdocs的使用": "mkdocs的使用.md"
  # - 关于: "about.md"

theme:
  name: material

plugins:
  - search