site_name: 引商刻羽，杂以流徵

nav:
  - 首页: "index.md"
  - 器:   "mkdocs的使用.md"

theme:
  name: material
  palette:
      primary: 'blue'

plugins:
  - search

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg