import os

Import('env')

env = env.Clone()

pwd     = os.getcwd()
src     = Glob('*.c')
# CPPPATH = [pwd]

env.Append(CPPPATH = [pwd])

# group = env.Library('mbedtls', src)
group = env.Object(src)

Return('group')
